-- '''
-- need to run following commands to make changes:
-- cd into pioreactor directory
-- git stash
-- git pull
-- git status

-- chmod +x install-db.sh
-- ./install-db.sh
-- '''
-- DROP TRIGGER IF EXISTS update_pioreactor_unit_activity_data_from_lightrod_temperatures;

-- CREATE TRIGGER IF NOT EXISTS update_pioreactor_unit_activity_data_from_lightrod_temperatures AFTER INSERT ON lightrod_temperatures
-- BEGIN
--     INSERT INTO pioreactor_unit_activity_data(
--         pioreactor_unit,
--         experiment,
--         timestamp,
--         LR_A_top_temp,
--         LR_A_middle_temp,
--         LR_A_bottom_temp,
--         LR_A_timestamp,
--         LR_B_top_temp,
--         LR_B_middle_temp,
--         LR_B_bottom_temp,
--         LR_B_timestamp,
--         LR_C_top_temp,
--         LR_C_middle_temp,
--         LR_C_bottom_temp,
--         LR_C_timestamp,
--         LR_D_top_temp,
--         LR_D_middle_temp,
--         LR_D_bottom_temp,
--         LR_D_timestamp,
--         LR_E_top_temp,
--         LR_E_middle_temp,
--         LR_E_bottom_temp,
--         LR_E_timestamp,
--         LR_F_top_temp,
--         LR_F_middle_temp,
--         LR_F_bottom_temp,
--         LR_F_timestamp,
--         LR_G_top_temp,
--         LR_G_middle_temp,
--         LR_G_bottom_temp,
--         LR_G_timestamp
--     ) VALUES (
--         new.pioreactor_unit,
--         new.experiment,
--         new.timestamp,
--         new.LR_A_top_temp,
--         new.LR_A_middle_temp,
--         new.LR_A_bottom_temp,
--         new.LR_A_timestamp,
--         new.LR_B_top_temp,
--         new.LR_B_middle_temp,
--         new.LR_B_bottom_temp,
--         new.LR_B_timestamp,
--         new.LR_C_top_temp,
--         new.LR_C_middle_temp,
--         new.LR_C_bottom_temp,
--         new.LR_C_timestamp,
--         new.LR_D_top_temp,
--         new.LR_D_middle_temp,
--         new.LR_D_bottom_temp,
--         new.LR_D_timestamp,
--         new.LR_E_top_temp,
--         new.LR_E_middle_temp,
--         new.LR_E_bottom_temp,
--         new.LR_E_timestamp,
--         new.LR_F_top_temp,
--         new.LR_F_middle_temp,
--         new.LR_F_bottom_temp,
--         new.LR_F_timestamp,
--         new.LR_G_top_temp,
--         new.LR_G_middle_temp,
--         new.LR_G_bottom_temp,
--         new.LR_G_timestamp
--     )
--     ON CONFLICT(experiment, pioreactor_unit, timestamp) DO UPDATE SET
--         LR_A_top_temp=excluded.LR_A_top_temp,
--         LR_A_middle_temp=excluded.LR_A_middle_temp,
--         LR_A_bottom_temp=excluded.LR_A_bottom_temp,
--         LR_A_timestamp=excluded.LR_A_timestamp,
--         LR_B_top_temp=excluded.LR_B_top_temp,
--         LR_B_middle_temp=excluded.LR_B_middle_temp,
--         LR_B_bottom_temp=excluded.LR_B_bottom_temp,
--         LR_B_timestamp=excluded.LR_B_timestamp,
--         LR_C_top_temp=excluded.LR_C_top_temp,
--         LR_C_middle_temp=excluded.LR_C_middle_temp,
--         LR_C_bottom_temp=excluded.LR_C_bottom_temp,
--         LR_C_timestamp=excluded.LR_C_timestamp,
--         LR_D_top_temp=excluded.LR_D_top_temp,
--         LR_D_middle_temp=excluded.LR_D_middle_temp,
--         LR_D_bottom_temp=excluded.LR_D_bottom_temp,
--         LR_D_timestamp=excluded.LR_D_timestamp,
--         LR_E_top_temp=excluded.LR_E_top_temp,
--         LR_E_middle_temp=excluded.LR_E_middle_temp,
--         LR_E_bottom_temp=excluded.LR_E_bottom_temp,
--         LR_E_timestamp=excluded.LR_E_timestamp,
--         LR_F_top_temp=excluded.LR_F_top_temp,
--         LR_F_middle_temp=excluded.LR_F_middle_temp,
--         LR_F_bottom_temp=excluded.LR_F_bottom_temp,
--         LR_F_timestamp=excluded.LR_F_timestamp,
--         LR_G_top_temp=excluded.LR_G_top_temp,
--         LR_G_middle_temp=excluded.LR_G_middle_temp,
--         LR_G_bottom_temp=excluded.LR_G_bottom_temp,
--         LR_G_timestamp=excluded.LR_G_timestamp;
-- END;


-- DROP TRIGGER IF EXISTS update_pioreactor_unit_activity_data_from_pbr_temperature;

-- CREATE TRIGGER IF NOT EXISTS update_pioreactor_unit_activity_data_from_pbr_temperature AFTER INSERT ON pbr_temperature
-- BEGIN
--     INSERT INTO pioreactor_unit_activity_data(
--         pioreactor_unit,
--         experiment,
--         timestamp,
--         pbr_temperature
--     ) VALUES (
--         new.pioreactor_unit,
--         new.experiment,
--         new.timestamp,
--         new.pbr_temperature
--     )
--     ON CONFLICT(experiment, pioreactor_unit, timestamp) DO UPDATE SET
--         pbr_temperature=excluded.pbr_temperature;
-- END;


-- DROP TRIGGER IF EXISTS update_pioreactor_unit_activity_data_from_plot_lightrod_temperatures;

-- CREATE TRIGGER IF NOT EXISTS update_pioreactor_unit_activity_data_from_plot_lightrod_temperatures AFTER INSERT ON plot_lightrod_temperatures
-- BEGIN
--     INSERT INTO pioreactor_unit_activity_data(
--         pioreactor_unit,
--         experiment,
--         timestamp,
--         max_temperature
--     ) VALUES (
--         new.pioreactor_unit,
--         new.experiment,
--         new.timestamp,
--         new.max_temperature
--     )
--     ON CONFLICT(experiment, pioreactor_unit, timestamp) DO UPDATE SET
--         max_temperature=excluded.max_temperature;
-- END;


-- DROP TRIGGER IF EXISTS update_pioreactor_unit_activity_data_from_density;

-- CREATE TRIGGER IF NOT EXISTS update_pioreactor_unit_activity_data_from_density AFTER INSERT ON density
-- BEGIN
--     INSERT INTO pioreactor_unit_activity_data(
--         pioreactor_unit,
--         experiment,
--         timestamp,
--         density
--     ) VALUES (
--         new.pioreactor_unit,
--         new.experiment,
--         new.timestamp,
--         new.density
--     )
--     ON CONFLICT(experiment, pioreactor_unit, timestamp) DO UPDATE SET
--         density=excluded.density;
-- END;


-- DROP TRIGGER IF EXISTS update_pioreactor_unit_activity_data_from_absolute_growth_rates;

-- CREATE TRIGGER IF NOT EXISTS update_pioreactor_unit_activity_data_from_absolute_growth_rates AFTER INSERT ON absolute_growth_rates
-- BEGIN
--     INSERT INTO pioreactor_unit_activity_data(
--         pioreactor_unit,
--         experiment,
--         timestamp,
--         absolute_growth_rate
--     ) VALUES (
--         new.pioreactor_unit,
--         new.experiment,
--         new.timestamp,
--         new.absolute_growth_rate
--     )
--     ON CONFLICT(experiment, pioreactor_unit, timestamp) DO UPDATE SET
--         absolute_growth_rate=excluded.absolute_growth_rate;
-- END;

-- DROP TRIGGER IF EXISTS update_pioreactor_unit_activity_data_from_specific_dilution_rates;

-- CREATE TRIGGER IF NOT EXISTS update_pioreactor_unit_activity_data_from_specific_dilution_rates AFTER INSERT ON specific_dilution_rates
-- BEGIN
--     INSERT INTO pioreactor_unit_activity_data(
--         pioreactor_unit,
--         experiment,
--         timestamp,
--         sdr
--     ) VALUES (
--         new.pioreactor_unit,
--         new.experiment,
--         new.timestamp,
--         new.sdr
--     )
--     ON CONFLICT(experiment, pioreactor_unit, timestamp) DO UPDATE SET
--         sdr=excluded.sdr;
-- END;

-- DROP TRIGGER IF EXISTS update_pioreactor_unit_activity_data_from_driver_intensity;

-- CREATE TRIGGER IF NOT EXISTS update_pioreactor_unit_activity_data_from_driver_intensity AFTER INSERT ON driver_intensity
-- BEGIN
--     INSERT INTO pioreactor_unit_activity_data(
--         pioreactor_unit,
--         experiment,
--         timestamp,
--         driver_intensity
--     ) VALUES (
--         new.pioreactor_unit,
--         new.experiment,
--         new.timestamp,
--         new.driver_intensity
--     )
--     ON CONFLICT(experiment, pioreactor_unit, timestamp) DO UPDATE SET
--         driver_intensity=excluded.driver_intensity;
-- END;

-- DROP TRIGGER IF EXISTS update_pioreactor_unit_activity_data_from_pbr_ph;

-- CREATE TRIGGER IF NOT EXISTS update_pioreactor_unit_activity_data_from_pbr_ph AFTER INSERT ON pbr_ph
-- BEGIN
--     INSERT INTO pioreactor_unit_activity_data(
--         pioreactor_unit,
--         experiment,
--         timestamp,
--         pbr_ph_ph
--     ) VALUES (
--         new.pioreactor_unit,
--         new.experiment,
--         new.timestamp,
--         new.pbr_ph_ph
--     )
--     ON CONFLICT(experiment, pioreactor_unit, timestamp) DO UPDATE SET
--         pbr_ph_ph=excluded.pbr_ph_ph;
-- END;